# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 01:24
from __future__ import unicode_literals

import audiofield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100, verbose_name='Frase')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('kanji', models.TextField(verbose_name='Kanji')),
                ('audio', audiofield.fields.AudioField(help_text='Allowed type - .mp3, .wav, .ogg', upload_to='cards/audios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
