# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 22:14
from __future__ import unicode_literals

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='audio',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', null=True, upload_to='cards/audios'),
        ),
    ]
