# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-22 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20160817_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['phrase'], 'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
    ]
